#!/usr/bin/env BratDisplayZFXYJasonSSH.cmd

#---------------------------------------------
# General parameters
#---------------------------------------------
#FILE = ${BRATHL_DATA_DIR}/JasonSSH133_135.nc

#FILE = ${BRATHL_DATA_DIR}/JasonSSH133_all.nc
#FILE = ${BRATHL_DATA_DIR}/JasonSSH134_all.nc
#FILE = ${BRATHL_DATA_DIR}/JasonSSH135_all.nc

#FILE = ${BRATHL_DATA_DIR}/JasonSSH109_all.nc
#FILE = ${BRATHL_DATA_DIR}/JasonSSH110_all.nc
#FILE = ${BRATHL_DATA_DIR}/JasonSSH111_all.nc
#FILE = ${BRATHL_DATA_DIR}/JasonSSH112_all.nc
#FILE = ${BRATHL_DATA_DIR}/JasonSSH116_all.nc
#FILE = ${BRATHL_DATA_DIR}/JasonSSH117_all.nc
#FILE = ${BRATHL_DATA_DIR}/JasonSSH119_all.nc
FILE = ${BRATHL_DATA_DIR}/JasonSSH120_all.nc

FILE = ${BRATHL_DATA_DIR}/JasonSLA109_all.nc

VERBOSE = 1

DISPLAY_GROUPBY_FILE = Y
DISPLAY_TITLE = Jason Sea Surface Height Comparison
DISPLAY_PROPERTIES = Y
DISPLAY_ANIMATIONBAR = N
DISPLAY_COLORBAR = Y
DISPLAY_CENTERLAT = 0
DISPLAY_CENTERLON = 0
DISPLAY_PROJECTION = 3d
#DISPLAY_COASTRESOLUTION = LOW



#---------------------------------------------
# Field parameters
#---------------------------------------------


FIELD		= SSH
DISPLAY_NAME = SSH 1
DISPLAY_MINVALUE = -80
DISPLAY_MAXVALUE = 80
DISPLAY_OPACITY = 0.7
DISPLAY_NUMCOLORLABELS = 4
DISPLAY_COLORTABLE = Ozone
#DISPLAY_COLORTABLE = ${BRATHL_DATA_DIR}/colorCustxx.ct
#DISPLAY_COLORCURVE  = sqrt
DISPLAY_CONTOUR = N
DISPLAY_CONTOUR_NUMBER = 3
DISPLAY_CONTOUR_LABEL = Y
DISPLAY_CONTOUR_MINVALUE = -80
DISPLAY_CONTOUR_MAXVALUE = 80
DISPLAY_SOLID_COLOR = Y

#FIELD		= SLA
#DISPLAY_NAME = SLA
#DISPLAY_MINVALUE = -1
#DISPLAY_MAXVALUE = 5
#DISPLAY_NUMCOLORLABELS = 6
#DISPLAY_COLORTABLE = Rainbow
#DISPLAY_CONTOUR = N
#DISPLAY_CONTOUR_NUMBER = 5
#DISPLAY_CONTOUR_LABEL = Y
#DISPLAY_CONTOUR_MINVALUE = 0
#DISPLAY_CONTOUR_MAXVALUE = 3
#DISPLAY_SOLID_COLOR = Y



#FIELD		= SSH
#DISPLAY_NAME = SSH 2
#DISPLAY_MINVALUE = -50
#DISPLAY_MAXVALUE = 50
#DISPLAY_NUMCOLORLABELS = 6
#DISPLAY_COLORTABLE = Rainbow
#DISPLAY_CONTOUR = N
#DISPLAY_SOLID_COLOR = Y

