#!/usr/bin/env BratDisplayZFXYEnvisatSSH.cmd

FILE = ${BRATHL_DATA_DIR}\EnvisatSSH35.nc
VERBOSE = 1

FIELD		= SSH

DISPLAY_PROPERTIES = Y
DISPLAY_ANIMATIONBAR = Y
DISPLAY_COLORBAR = N
DISPLAY_CENTERLAT = 90
DISPLAY_CENTERLON = -90
DISPLAY_MINVALUE = -80
DISPLAY_MAXVALUE = 83.5
DISPLAY_OPACITY = 0.5
DISPLAY_PROJECTION = mercator
DISPLAY_NUMCOLORLABELS = 5
DISPLAY_COLORTABLE = ozone
DISPLAY_COASTRESOLUTION = intermediate
